const string name = "Aldair"; 
int age;
const double height = 1.77;
age = 23;
Console.Write($"Name: {name}");
Console.WriteLine("");
Console.Write($"Age: {age}");
Console.WriteLine("");
Console.Write($"Height: {height}cm");
Console.WriteLine("");